http:
  port: ${PORT:-8080}
admin:
  port: ${PORT_ADMIN:-9876}
  host: localhost
apiEndpoints:
  agenda:
    host: '*'
    paths: '/agenda/*'
  auth:
    host: '*'
    paths: '/auth/*'
  users:
    host: '*'
    paths: '/users/*'
serviceEndpoints:
  agenda:
    url: ${APIAgenda}
  auth:
    url: ${APIAuth}
  users:
    url: ${APIUsers}
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  pipeline_agenda:
    apiEndpoints:
      - agenda
    policies:
      - proxy:
          action:
            serviceEndpoint: agenda
            changeOrigin: true
  pipeline_auth:
    apiEndpoints:
      - auth
    policies:
      # - key-auth:
      # - cors:
      #     action:
            # origin: true
            # origin: 'http://localhost:4200'
            # credentials: true
            # methods: 'HEAD,PUT,PATCH,POST,DELETE'
            # allowedHeaders: 'X-TEST'
      - proxy:
          action:
            serviceEndpoint: auth
            changeOrigin: true
  pipeline_users:
    apiEndpoints:
      - users
    policies:
      # - key-auth:
      - proxy:
          action:
            serviceEndpoint: users
            changeOrigin: true
